
IMAGE_HEIGHT = 240

IMAGE_WIDTH = 320

FILTER_SIZES = [15, 5]

MAX_POOLING_SIZES = [2, 2]

# noinspection PyListCreation
IMAGE_HEIGHTS = []
IMAGE_HEIGHTS.append(IMAGE_HEIGHT)
IMAGE_HEIGHTS.append((IMAGE_HEIGHTS[0] - FILTER_SIZES[0] + 1) // 2)
IMAGE_HEIGHTS.append((IMAGE_HEIGHTS[1] - FILTER_SIZES[1] + 1) // 2)

# noinspection PyListCreation
IMAGE_WIDTHS = []
IMAGE_WIDTHS.append(IMAGE_WIDTH)
IMAGE_WIDTHS.append((IMAGE_WIDTHS[0] - FILTER_SIZES[0] + 1) // 2)
IMAGE_WIDTHS.append((IMAGE_WIDTHS[1] - FILTER_SIZES[1] + 1) // 2)
